# Generated by Django 4.1.3 on 2022-11-28 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_students_teachers_delete_student_delete_teacher_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
        migrations.RenameModel(
            old_name='Teachers',
            new_name='Teacher',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='teachers',
            new_name='teacher',
        ),
    ]
